apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-create-container-error
  labels:
    run: deployment-create-container-error
    type: test-pod
  "annotations": {
    "dsn" : "https://474d9da00094c5e39d6800c01f3aeff6@o4506191942320128.ingest.sentry.io/4506363396816896",
  }
spec:
  replicas: 2
  selector:
    matchLabels:
      run: deployment-create-container-error
      type: test-pod
  template:
    metadata:
      labels:
        run: deployment-create-container-error
        type: test-pod
    spec:
      containers:
        - image: alpine:3
          name: deployment-create-container-error
          env:
            - name: SOMETHING
              valueFrom:
                configMapKeyRef:
                  name: configmap-does-nont-exist
                  key: key
