apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-outofmemory
    type: test-pod
  name: pod-outofmemory
  "annotations": {
    "dsn" : "https://474d9da00094c5e39d6800c01f3aeff6@o4506191942320128.ingest.sentry.io/4506363396816896",
  }
spec:
  containers:
    - image: python:3.10-alpine
      name: container-outofmemory
      command:
        - python
        - "-c"
        - |
          import os, resource, time

          ar = bytearray(0)
          while True:
            print(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss)
            ar += bytearray(10 ** 10)
            time.sleep(0.5)
      resources:
        requests:
          cpu: 100m
          memory: 10Mi
        limits:
          cpu: 100m
          memory: 10Mi
  restartPolicy: Always
