name: Test
on:
  push:
    branches:
      - master
      - main
      - release/**
      - test/**
      - build/**
  pull_request:
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  test:
    name: All
    runs-on: ${{ matrix.os }}-latest
    env:
      GOFLAGS: "-mod=readonly"
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: Build
        run: make build
      - name: Vet
        run: make vet
      - name: Check go.mod Tidiness
        run: make mod-tidy
      - name: Test
        run: make test
      - name: Upload coverage reports to Codecov
        # https://github.com/codecov/codecov-action/releases/tag/v3.1.4
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: .coverage
    timeout-minutes: 10
    strategy:
      matrix:
        go: ["1.20"]
        os: [ubuntu]
      fail-fast: false
