name: Test

on:
  push:
    branches:
      - master
      - main
      - release/**
      - test/**
      - build/**
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    name: All
    runs-on: ubuntu-latest
    env:
      GOFLAGS: "-mod=readonly"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build
        run: make build
      - name: Vet
        run: make vet
      - name: Check go.mod Tidiness
        run: make mod-tidy
      - name: Test
        run: make test-coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: .coverage
